name: Pruner
on:
  pull_request:
  push:
    tags: ['[0-9]+.[0-9]+.[0-9]+']

permissions:
  contents: read
  security-events: write
  id-token: write
  attestations: write

jobs:
  audit:
    uses: ob-aion/pruner/.github/workflows/reusable-full-scan.yml@0.1.1
    with:
      fail-on: critical
