name: Pruner
on:
  pull_request:
  push:
    tags: ['[0-9]+.[0-9]+.[0-9]+']

permissions:
  contents: read
  security-events: write
  id-token: write
  attestations: write

jobs:
  audit:
    # Replace <VERSION> with the latest tag from https://github.com/ob-aion/pruner/releases/latest
    uses: ob-aion/pruner/.github/workflows/scan.yml@<VERSION>
    with:
      fail-on: critical
