name: self-scan
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pruner-self-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write   # github/codeql-action/upload-sarif
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - id: scan
        uses: ./
        with:
          fail-on: critical
          target-path: '.'
          report-output: ./.pruner

      - if: ${{ always() }}
        name: Upload report bundle
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: pruner-self-scan-report
          path: .pruner/
          retention-days: 14
